# Generated by Django 4.2.9 on 2025-03-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='department',
            field=models.CharField(max_length=200),
        ),
    ]
